project:
  type: website
  resources:
    - "icons/"

execute:
  freeze: auto

website:
  title: "PSYC894"
  navbar:
    background: primary
    search: true
    right:
      - href: https://canvas.ku.edu/courses/182539
        icon: mortarboard
        text: "Canvas"
      - href: https://canvas.ku.edu/courses/182539
        icon: file-text
        text: "Syllabus"
      - href: schedule.qmd
        icon: calendar
        text: "Schedule"
      - text: "Unit A"
        menu:
          - icon: code-square
            text: "Week 01: Overview and Workflow"
            href: A/01/index.html
          - icon: graph-up
            text: "Week 02: Linear Modeling Recap"
            href: A/02/index.html
          - icon: cone-striped
            text: "Week 03: Clustering Issues and Approaches"
            href: A/03/index.html
          - icon: tools
            text: "Week 04: Data Prep and Estimation"
            href: A/04/index.html
      - text: "Unit B"
        menu:
          - icon: arrow-down-up
            text: "Week 05: Random Intercept Models"
            href: B/05/index.html
          - icon: shuffle
            text: "Week 06: Random Slope Models"
            href: B/06/index.html
          - icon: arrow-down-right
            text: "Week 07: Cross-level Interactions"
            href: B/07/index.html
          - icon: translate
            text: "Week 08: Translation Activity"
            href: B/08/index.html
      - text: "Unit C"
        menu:
          - icon: balloon
            text: "Week 09: Spring Break"
            href: C/09/index.html
          - icon: chevron-right
            text: "Week 10: Model Comparison"
            href: C/10/index.html
          - icon: alarm
            text: "Week 11: Longitudinal Analyses"
            href: C/11/index.html
          - icon: journal-medical
            text: "Week 12: Diagnostics and Reporting"
            href: C/12/index.html
      - text: "Unit D"
        menu:
          - icon: gear
            text: "Week 13: Troubleshooting and Bayes"
            href: D/13/index.html
          - icon: building-up
            text: "Week 14: Advanced Previews"
            href: D/14/index.html
          - icon: briefcase
            text: "Week 15: Project Work"
            href: D/15/index.html
          - icon: briefcase
            text: "Week 16: Project Work"
            href: D/16/index.html
  page-footer: "Copyright 2026 &copy; Jeffrey Girard"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



